SELECT ARTIST, AVG(SONG.DUR) AS AvgDuration
FROM ARTIST
INNER JOIN SONG ON ARTIST.TITLEID = SONG.TITLEID
GROUP BY ARTIST
HAVING COUNT(SONG.TITLEID) >= 3 
ORDER BY AvgDuration DESC
FETCH NEXT 5 ROWS ONLY;

